app/players/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, Response
from sqlalchemy import desc
from sqlalchemy.sql import collate
from functools import wraps

from app import db

from app.database.database import Mission, Player, AIMovement, PlayerMovement, PlayerDisconnect, func, CmpPlayer
from app.sessions.models import Session, SessionMission
from app.login.routes import requires_auth

import time
import collections
import json
import datetime

mod_players = Blueprint('players', __name__, url_prefix='/players',
                       template_folder='templates')


@mod_players.route('/')
@requires_auth
def display_players():
    players_in_database = db.session.query(CmpPlayer).order_by(CmpPlayer.danger_zone.desc(), CmpPlayer.last_played, CmpPlayer.player_rank).all()

    ranks = []

    for player in players_in_database:
        ranks.append(player.player_rank)

    unique_ranks = set(ranks)

    data = dict.fromkeys(unique_ranks, 0)

    for rank in ranks:
        data[rank] = (data[rank] + 1)

    return render_template('players.html', players=players_in_database, data=data, today=datetime.date.today())

@mod_players.route('/note/<username>', methods=['PUT'])
@requires_auth
def submit_notes(username):
    if username is None:
        return 'No username was given!', 404
    notes = request.json
    player = db.session.query(CmpPlayer).filter(CmpPlayer.player_name == username).first()
    if player is None:
        return 'Username not found!', 404
    player.staff_notes = notes
    db.session.commit()
    return '', 201


@mod_players.route('/<username>')
@requires_auth
def display_one_player(username):

    displayed_player = db.session.query(CmpPlayer).filter(CmpPlayer.player_name == username).first()
    if displayed_player is None:
        return redirect(url_for('.display_players'))
        
    all_players_arma = db.session.query(Player).filter(Player.player_name == username).all() 
    selected_player_arma = [player for player in all_players_arma if ((player.created.weekday() in [5, 6]) # Retrieve the player we are looking for from db
                                                                        and ((player.created.hour >= 18) or (player.created.hour <= 5)) 
                                                                        and (player.is_jip == False) 
                                                                        and (player.player_name == username))]
    
    player_roles = []
    
    for player in selected_player_arma:
            player_roles.append(player.hull_gear_class)
    
    unique_roles = set(player_roles)
    
    data = dict.fromkeys(unique_roles, 0)
    
    for role in player_roles:
        data[role] = (data[role] + 1)
    
    
    return render_template('profile.html', player=displayed_player, data=data)

app/players/templates/players.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Arma 2 players</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.23.3/js/jquery.tablesorter.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="{{ url_for('static', filename='chartkick.js') }}"></script>
    <script src="{{ url_for('static', filename='js/players.js') }}"></script>
    <script src="{{ url_for('static', filename='js/charts.js') }}"></script>
</head>
<body>
<div class="container">
    <div class="header">
        <div class="navigation">
            <div class="navigation-button"><a href="{{url_for('sessions.get_sessions')}}"}}>Sessions</a></div>
            <div class="navigation-button active"><a href="{{url_for('players.display_players')}}">Players</a></div>
            <div class="navigation-button"><a href="{{url_for('missions.display_missions')}}"}}>Missions</a></div>
            </ul>
        </div>
    </div>
    <div class="content">
        <div class="charts">
            <div class="chart">
                <div class="chart-header">
                    <span>Rank distribution</span>
                </div>
                <div class="chart-content hidden">
                    {% pie_chart data with id='chart-1' height='400px' %}
                </div>
            </div>
        </div>
        <div>
            <table id="players" class="players">
                <thead>
                    <tr>
                        <th class="text-left">
                            Username
                            <span class="sort-icons">
                                <img class="asc" width="10" src="{{ url_for('static', filename='icon/asc.png') }}"/>
                                <img class="desc" width="10" src="{{ url_for('static', filename='icon/desc.png') }}"/>
                            </span>
                        </th>
                        <th class="text-center">
                            Rank
                            <span class="sort-icons">
                                <img class="asc" width="10" src="{{ url_for('static', filename='icon/asc.png') }}"/>
                                <img class="desc" width="10" src="{{ url_for('static', filename='icon/desc.png') }}"/>
                            </span>
                        </th>
                        <th class="text-center">
                            Played
                            <span class="sort-icons">
                                <img class="asc" width="10" src="{{ url_for('static', filename='icon/asc.png') }}"/>
                                <img class="desc" width="10" src="{{ url_for('static', filename='icon/desc.png') }}"/>
                            </span>
                        </th>
                        <th class="text-center">
                            Last played
                            <span class="sort-icons">
                                <img class="asc" width="10" src="{{ url_for('static', filename='icon/asc.png') }}"/>
                                <img class="desc" width="10" src="{{ url_for('static', filename='icon/desc.png') }}"/>
                            </span>
                        </th>
                        <th class="text-left">
                            Staff note
                            <span class="sort-icons">
                                <img class="asc" width="10" src="{{ url_for('static', filename='icon/asc.png') }}"/>
                                <img class="desc" width="10" src="{{ url_for('static', filename='icon/desc.png') }}"/>
                            </span>
                        </th>
                        <th class=""></th>
                    <tr>
                </thead>
                <tbody>
                {% for player in players %}  
                    <!--<tr class="{{player.return_danger()}} {{player.player_rank}}" >-->
                    <tr>
                        <td class="username text-left"><a href="{{url_for('players.display_one_player', username=player.player_name)}}">{{player.player_name}}</a></td>
                        <td class="rank text-center {{ player.player_rank }}">{{ player.player_rank }}</td>
                        <td class="played text-center">{{player.missions_played}}</td>
                        <td class="last-played text-center" title="{{ player.last_played.date() }}">
                            {{ 'today' if (today - player.last_played.date()).days <= 0 else (today - player.last_played.date()).days ~ ' days ago' }}
                        </td>
                        <td class="note text-left">
                            <span class="note-value" data-username="{{ player.player_name }}">{{ player.staff_notes }}</span>
                            <span class="note-edit" style="display: none;"><input name="note" value="{{ player.staff_notes }}"/></span>
                        </td>
                        <td class="operations">
                            <button class="update" style="display: none;">Update</button>
                            <button class="cancel" style="display: none;">Cancel</button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>

app/players/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{player.player_name}}'s profile</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="{{ url_for('static', filename='chartkick.js') }}"></script>
    <script src="{{ url_for('static', filename='js/charts.js') }}"></script>
</head>
<body>
<div class="container">
    <div class="header">
        <div class="navigation">
            <div class="navigation-button"><a href="{{url_for('sessions.get_sessions')}}"}}>Sessions</a></div>
            <div class="navigation-button profile active"><a href="{{ url_for('players.display_players') }}">Players</a> / {{player.player_name}}</div>
            <div class="navigation-button"><a href="{{url_for('missions.display_missions')}}"}}>Missions</a></div>
            </ul>
        </div>
    </div>
    <div class="content">
        <div class="profile-stats">
            <div class="field-content">
                <div class="row">
                    <div class="field">
                        <span class="label">Rank:</span>
                        <span class="value">{{ player.player_rank }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="field">
                        <span class="label">UID:</span>
                        <span class="value">{{ player.player_uid }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="field">
                        <span class="label">Deaths / played:</span>
                        <span class="value" title="{{ '%.2f' % (player.deaths / player.missions_played * 100) }} %">{{ player.deaths }} / {{ player.missions_played }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="field">
                        <span class="label">Leadership / played:</span>
                        <span class="value" title="{{ '%.2f' % (player.played_leader / player.missions_played * 100) }} %">{{ player.played_leader }} / {{ player.missions_played }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="field">
                        <span class="label">Last session:</span>
                        <span class="value">
                            <a href="{{url_for('sessions.display_session', year=player.last_played.year, week=player.last_played.isocalendar()[1]) }}">
                                {{ player.last_played.year }} / {{ player.last_played.isocalendar()[1] }}
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="charts">
            <div class="chart">
                <div class="chart-header">
                    <span>Role distribution</span>
                </div>
                <div class="chart-content" >
                    {% pie_chart data with id='chart-1' height='400px' %}
                </div>
            </div>
        </div>
    </div>
</div>
</body>