app/missions/models.py
import time
from datetime import date
import datetime
import os
import re

from app.database.database import Mission
from app import db
from app import app


class MissionData:
	def __init__(self, mission_name, played):
		self.mission_name = mission_name
		self.played = played
		self.mission_type = "co"
		if played is not 0:
			mission_all = db.session.query(Mission).filter(Mission.mission_name == mission_name).all()
			temp_mission = mission_all[0]
			for mission in mission_all:
				if temp_mission.created < mission.created:
					temp_mission = mission

			self.last_played = temp_mission.created.date()
			self.last_datetime = temp_mission.created.date()
		else:
			self.last_played = "No record"
			self.last_datetime = datetime.date(datetime.MINYEAR, 1, 1)

		self.colour = self.setColour()

		if self.mission_name != "##Lobby##":
			split_mission_name = self.mission_name.split("_")[1]
			if split_mission_name[:3] in ["gtv", "tvt"]:
				self.mission_type = "tvt"


	def __eq__(self, other):
		return self.mission_name == other


	def setColour(self):
		value = abs(self.last_datetime.isocalendar()[1] - date.today().isocalendar()[1])
		returnValues = {
			0 : "stage1",
			1 : "stage1",
			2 : "stage2",
			3 : "stage2",
			4 : "stage3",
			5 : "stage3",
			6 : "stage4",
			7 : "stage4",
			8 : "stage5",
		}

		return returnValues.get(value, "stage5")


class PBO:
	def __init__(self, pbo):
		if pbo is None:
			raise

		self.name = os.path.basename(pbo.filename)

		if self.valid_name(self.name):
			self.mission = MissionData(self.name, 0)
			pbo.save(os.path.join(app.config['UPLOAD_FOLDER'], pbo.filename))
		else:
			raise

	def valid_name(self, name):
		return (True if	re.search('ark+_[a-z]+[0-9]+_.+[.].+[.]pbo', name)
				else False)

app/missions/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, Response
from sqlalchemy import desc
from functools import wraps
from itertools import chain
from collections import Counter

import os
import re

from app import db

from app.database.database import Mission, Player, AIMovement, PlayerMovement, PlayerDisconnect, func, CmpPlayer
from app.sessions.models import Session, SessionMission
from app.login.routes import requires_auth
from .models import MissionData


mod_missions = Blueprint('missions', __name__, url_prefix='/missions',
                       template_folder='templates')


@mod_missions.route('/')
@requires_auth
def display_missions():
	session_missions = missions_in_db()
	folder_missions = missions_in_folder()

	counted_missions = Counter(session_missions)
	missions_data = []

	for key, value in counted_missions.items():
		missions_data.append(MissionData(key.mission_name, key.world_name, value))


	for mission in folder_missions:
		if mission not in missions_data:
			missions_data.append(MissionData(mission[0], mission[1], 0))

	missions_data.sort(key=lambda x: x.last_datetime, reverse=True)

	return render_template('missions.html', missions=missions_data)

def is_session_mission(mission):
	return ((mission.created.weekday() in [5,6]) and ((mission.created.hour >= 18) or (mission.created.hour <= 5)) and not len(mission.mission_name.split("_")) < 3)

def missions_in_folder():
	folder_missions = []

	for file in os.listdir("C:/dev/python/arma2oa/MPMissions"):
		if file.endswith(".pbo"):
			temp_name = re.sub('(?:[.](.*)|_[vV]([0-9]+(.*))?)', '', file)
			world_name = file.split('.')[1]
			folder_missions.append([temp_name, world_name])

	return folder_missions

def missions_in_db():
	missions = db.session.query(Mission).all()
	session_missions = [mission for mission in missions if is_session_mission(mission)]

	for mission in session_missions:
		mission.mission_name = re.sub('(_[vV]([0-9]+)?)$', '', mission.mission_name)

	return session_missions

app/missions/templates/missions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Arma 2 missions</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="{{ url_for('static', filename='js/missions.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple.css') }}">
</head>
<body>
<div class="container">
    <div class="header">
        <h1>Arma 2 missions</h1>
        <div class="navigation">
            <div class="navigation-button"><a href="{{url_for('sessions.get_sessions')}}"}}>Sessions</a></div>
            <div class="navigation-button"><a href="{{url_for('players.display_players')}}">Players</a></div>
            <div class="navigation-button active"><a href="{{url_for('missions.display_missions')}}"}}>Missions</a></div>
            </ul>
        </div>
    <div>
    <div>
    {% for mission in missions %}
        <div class="mission-container {{mission.colour}}">
            <div class="mission-header">
                <div class="mission-type {{ mission.type }}">{{ mission.type_html().upper()}}</div>
                <div class="mission-player-count">{{ mission.player_count }}</div>
                <div class="mission-name"><span class="mission-collapse">{{ mission.mission_name }}</span></div>
                <div class="mission-world">{{mission.world_name}}</div>
            </div>
            <div class="field-content" style="display: none;">
                <div class="row">
                    <div class="field">
                        <span class="label">Last played:</span>
                        <span class="value">{{mission.last_played}}
                        {% if mission.played > 0 %}
                            , {{ mission.last_played_delta }} days ago
                        {% endif %}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="field">
                        <span class="label">Mission type:</span>
                        <span class="value mission-type {{mission.type}}">{{ mission.type.upper() }}</span>
                    </div>
                </div>
                {% if mission.played > 0 %}
                <div class="row">
                    <div class="field">
                        <span class="label">Session:</span>
                        <span class="value"><a href="{{url_for('sessions.display_session', year=mission.last_datetime.year, week=mission.last_datetime.isocalendar()[1]) }}">
                        {{ mission.last_datetime.year }} / {{ mission.last_datetime.isocalendar()[1] }}</a></span>
                    </div>
                </div>
                <div class="row">
                    <div class="field">
                        <span class="label">Nr of runs:</span>
                        <span class="value">{{mission.played}}</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    </div>
</div>
</body>
</html>